# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Important to Drop the Heroku DB or reset db use the below command
#
# heroku pg:reset DATABASE_URL --confirm cvbuilder ( No Need )
# heroku run rake db:reset 
# heroku run rake db:migrate

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cv_builder_db
  pool: 5
  username: root
  password: asdfgh
  

fast_mode:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: cv_builder_db
  pool: 5
  username: root
  password: asdfgh
  

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: cv_builder_db
  pool: 5
  username: root
  password: asdfgh
##  socket: /var/run/mysqld/mysqld.sock
  port: 5432
  host: localhost
  

